# Generated by Django 5.1.7 on 2025-06-26 04:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuariopersonalizado_biografia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariopersonalizado',
            name='avatar',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='avatar'),
        ),
    ]
