# Generated by Django 5.1.7 on 2025-05-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleccionables', '0002_alter_coleccionable_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
