# Generated by Django 5.1.7 on 2025-05-08 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleccionables', '0003_categoria_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coleccionable',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coleccionable', to='coleccionables.categoria'),
        ),
    ]
