# Generated by Django 5.1.7 on 2025-05-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleccionables', '0004_alter_coleccionable_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='categorias/'),
        ),
    ]
