# Generated by Django 5.1.7 on 2025-05-20 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coleccionables', '0006_carrito_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='creado',
        ),
        migrations.AddField(
            model_name='carrito',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='carrito',
            name='coleccionable',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coleccionables.coleccionable'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
